language: r
r:
  - release
  - oldrel
  - devel

cache: packages

os:
  - linux

sudo: required

#fussy building for CRAN compatibility
warnings_are_errors: true
r_check_args: --as-cran

R_binary_packages:
  - Rcpp
  - methods
  - Matrix
  - R6

matrix:
  include:
    - os: osx
      r: release
      disable_homebrew: true
    - os: osx
      r: oldrel
      disable_homebrew: true
    - os: osx
      r: devel
      disable_homebrew: true
    - os: osx
      r: release
      disable_homebrew: false
    - os: osx
      r: oldrel
      disable_homebrew: false
    - os: osx
      r: devel
      disable_homebrew: false
