language: r
r:
  - release
  # Test on old / devel versions ?
  # - oldrel
  # - devel

cache: packages

os:
  # - linux
  - osx

#fussy building for CRAN compatibility
warnings_are_errors: true
r_check_args: --as-cran
disable_homebrew: true 
