language: r
r:
  - release
 #  - oldrel
 #  - devel

cache: packages

os:
  # - linux
  - osx
  # - windows

sudo: required

#fussy building for CRAN compatibility
warnings_are_errors: true
r_check_args: --as-cran
disable_homebrew: true

R_binary_packages:
  - Rcpp
  - methods
  - Matrix
  - R6
